name: emp_system
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  get: ^4.7.2
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  google_maps_flutter: ^2.10.1
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  geocoding: ^3.0.0
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: VarelaRounded
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
  assets:
    - assets/images/